### ISSUE TITLE
GPIOnext Config not working

### ISSUE THREAD

**Issue by HephaestusHex** [mholgatem/GPIOnext#64]
Sorry for posting, I just couldn't work the issue out with previous threads.

So, when I run "gpionext config" to configure the buttons, 
it gives and error that says:

Traceback (most recent call last):
  File "/home/pi/GPIOnext/config_manager.py", line 315, in <module>
    ConfigurationManager(args)
  File "/home/pi/GPIOnext/config_manager.py", line 85, in __init__
    gpio.setupGPIO( self.args )
  File "/home/pi/GPIOnext/config/gpio.py", line 99, in setupGPIO
    pins.append( pin(pinNumber, pull, args) )
  File "/home/pi/GPIOnext/config/gpio.py", line 59, in __init__
    bouncetime = args.debounce)
RuntimeError: Failed to add edge detection

I don't understand what is going on and how to fix it.

**Comment by HephaestusHex** [comment]
Update: I will try to reinstall RetroPie
